name: Deploy

on:
  push:
  schedule:
  - cron: '15 5 * * 0'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v2

    - name: Checkout gh-pages branch
      uses: actions/checkout@v2
      with:
        path: gh-pages
        ref: gh-pages

    - name: Set up Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 12.x

    - name: Get yarn cache directory path
      id: yarn-cache-dir-path
      run: echo "::set-output name=dir::$(yarn cache dir)"

    - uses: actions/cache@v2
      id: yarn-cache # use this to check for `cache-hit` (`steps.yarn-cache.outputs.cache-hit != 'true'`)
      with:
        path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
        key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
        restore-keys: |
          ${{ runner.os }}-yarn-


    - name: Install dependencies
      run: yarn

    - name: Run linter
      run: yarn lint

    - name: Build the app
      run: yarn build

    - name: Commit and push
      if: github.ref == 'refs/heads/master'
      run: |
        cd gh-pages
        git config --local user.email "location-finder@noreply.github.com"
        git config --local user.name "GitHub Actions"
        cp -R ../dist/ .
        git add .
        git diff --cached --quiet || git commit -m "Rebuild app"
        git push origin HEAD
